- name: Downloading Nodejs repo file
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_19.x | sudo -E bash -

- name: Installing Nodejs server
  ansible.builtin.yum:
    name: nodejs
    state: latest

- name: Configuring app_start
  ansible.builtin.include_tasks:
    file: app_start.yml

- name: Installing Nodejs dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Copying service file
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Loading Mongo schema
  ansible.builtin.include_tasks:
    file: mongo_schema.yml
  when: load_schema

- name: Service Restartng and Enabling
  ansible.builtin.include_tasks:
    file: service_start.yml
